# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cm9vdDEyMyEh  # echo -n 'root123!!' | base64
  password: cGFzc3dvcmQxMjM=   # echo -n 'password123' | base64